# tips hat to PÃ¡draic Brady, Dave Marshall, Wouter, Graham Campbell for this
language: php

php:
  - 5.6
  - 7.0

matrix:
  allow_failures:
    - php: 7.0

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_install:
    - composer self-update

install:
    - export PATH="$HOME/.composer/vendor/bin:$PATH"
    - travis_retry ./travis/install.sh

before_script:
    - composer install
    - wget https://s3-us-west-2.amazonaws.com/csvelte/csvsampledata.tar.gz
    - tar xvfz csvsampledata.tar.gz -C tests/
    - echo 'date.timezone = "America/Los_Angeles"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

script:
    - ./travis/script.sh

after_script:
    - ./travis/after_script.sh

notifications:
  email:
    - luke.visinoni@gmail.com
    - luke@visinoni.net
